// apps/reactapp/src/app/app.tsx
import * as React from 'react';
import { Component } from 'react';

import './app.scss';

export class App extends Component {
  render() {
    const title = 'reactapp';
    return (
      <div>
        <div style={{ textAlign: 'center' }}>
          <h1>Welcome to {title}!</h1>
          <happynrwl-greeting title={title} />
          <img
            width="450"
            src="https://raw.githubusercontent.com/nrwl/nx/master/nx-logo.png"
          />
        </div>
        <p>
          This is a React app built with <a href="https://nx.dev">Nx</a>.
        </p>
        <p>
          🔎 **Nx is a set of Angular CLI power-ups for modern development.**
        </p>
        <h2>Quick Start & Documentation</h2>
        <ul>
          <li>
            <a href="https://nx.dev/getting-started/what-is-nx">
              30-minute video showing all Nx features
            </a>
          </li>
          <li>
            <a href="https://nx.dev/tutorial/01-create-application">
              Interactive tutorial
            </a>
          </li>
        </ul>
      </div>
    );
  }
}

// apps/angularapp/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'happynrwl-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angularapp';
}

<div style="text-align:center">
  <h1>Welcome to {{ title }}!</h1>
  <happynrwl-greeting [title]="title"></happynrwl-greeting>
  <img
    width="450"
    src="https://raw.githubusercontent.com/nrwl/nx/master/nx-logo.png"
  />
</div>

<p>This is an Angular app built with <a href="https://nx.dev">Nx</a>.</p>
<p>🔎 **Nx is a set of Angular CLI power-ups for modern development.**</p>

<h2>Quick Start & Documentation</h2>

<ul>
  <li>
    <a href="https://nx.dev/getting-started/what-is-nx"
      >30-minute video showing all Nx features</a
    >
  </li>
  <li>
    <a href="https://nx.dev/tutorial/01-create-application"
      >Interactive tutorial</a
    >
  </li>
</ul>
